import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


const sfReg = localFont({
  src: "../../public/assets/fonts/SF-Pro-Display-Regular.otf",
  variable: "--font-sfReg"
});

const sfBlack = localFont({
  src: "../../public/assets/fonts/SF-Pro-Display-Black.otf",
  variable: "--font-sfBlack",
})


const sfBold = localFont({
  src: "../../public/assets/fonts/SF-Pro-Display-Bold.otf",
  variable: "--font-sfBold"
})

const ppMontreal = localFont({
  src: "../../public/assets/fonts/ppneuemontreal-medium.otf",
  variable: "--font-ppMontreal"
})

export const metadata: Metadata = {
  title: "KEEP-UP",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sfReg.variable} ${sfBold.variable} ${sfBlack.variable} ${ppMontreal.variable} antialiased`}
      >
            {children}
      </body>
    </html>
  );
}
